version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: peghgo_db
      POSTGRES_USER: peghgo_user
      POSTGRES_PASSWORD: peghgo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://peghgo_user:peghgo_password@db:5432/peghgo_db

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: