# Generated by Django 5.0.3 on 2024-11-01 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=11, unique=True)),
                ('mobile_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile phone number.', regex='^\\d{2} \\d{5}-\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peghgo.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_background', models.ManyToManyField(to='peghgo.academicbackground')),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peghgo.contactinformation')),
                ('experiences', models.ManyToManyField(to='peghgo.professionalexperience')),
                ('personal_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peghgo.personalinformation')),
                ('skills', models.ManyToManyField(to='peghgo.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_background', models.ManyToManyField(related_name='candidates', to='peghgo.academicbackground')),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='peghgo.contactinformation')),
                ('personal_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='peghgo.personalinformation')),
                ('experiences', models.ManyToManyField(related_name='candidates', to='peghgo.professionalexperience')),
                ('skills', models.ManyToManyField(related_name='candidates', to='peghgo.skill')),
            ],
        ),
    ]
